nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/rancher-version: ">= 2.9.0-0"
    catalog.cattle.io/display-name: CAPI UI
    catalog.cattle.io/experimental: "true"
